### ISSUE TITLE
By default the Myserver.java file has errors. AfricasTalking.initialize doesn't work.

### ISSUE THREAD

**Issue by abedyngash** [Ian-Cornelius/ATOnDroid#3]

**Comment by Ian-Cornelius** [comment]
Ensure userName and APIKey values are okay.

**Comment by Ian-Cornelius** [comment]
Send your log output here. Ensure you have filtered to show current application.

**Comment by abedyngash** [comment]
Error: Program type already present: android.support.v4.app.BackStackRecord$Op

**Comment by abedyngash** [comment]
Resolved this by adding the appCompat-v4 dependency on the module:app gradle file
